### ISSUE TITLE
[object Object] bug?

### ISSUE THREAD

**Issue by dmalan** [cs50/harvard.cs50.statuspage#3]
![screen shot 2017-08-19 at 6 31 54 pm](https://user-images.githubusercontent.com/788678/29490509-bd1930ba-850c-11e7-8c23-ac96c444ba87.png)

**Comment by kzidane** [comment]
This suggests the name of the bottom incident was an object not a string somehow, which might've been a glitch in statuspage's API at the time this incident was fetched? I'm literally [storing the value they give back](https://github.com/cs50/harvard.cs50.statuspage/blob/master/statuspage.js#L110), which they promise to be a string per http://cs50.statuspage.io/api#incidents. The top incident supports this claim since it got stored the same way, and yet it got rendered correctly.

Want me to check whether it's a string before storing it and maybe log it to the console if not? This means we might miss some incidents, but we should be able to see what we got back from statuspage in case this happens again.

**Comment by dmalan** [comment]
Mind opening a ticket with them first, showing them that line of code and a
sample object we're getting back from the API?

**Comment by kzidane** [comment]
I wasn't able to replicate this, so I don't have a sample object of what we got back, but I'll ask them if it's possible for it to ever be an object instead of a string.

**Comment by dmalan** [comment]
Okay!

**Comment by kzidane** [comment]
Should be fixed.
